+++
title = "About"
+++baseURL = ''
languageCode = 'en-us'
title = 'life iyyyyyy
n a vacuum'
theme="etch-hugo"


[params]
  description = "description"
  copyright = "Copyright © 2022 dylan brandon"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  
